### ISSUE TITLE
Question about old utility: what did the spoof admin do in blooket-hack (old) ?

### ISSUE THREAD

**Issue by hxc4life07** [ThatFruedDued/blooket-utility-injectables#14]
Hi, I hace the doubt about the spoof admin feature.
If it gets to the point ofrece bypassing sometimes the side-server, what should the spoof admin offer you?

Thank you for resolving my doubts

**Comment by hxc4life07** [comment]
I used it when that version of blooket-hack was alive and it did nothing
 The spoofed plus used to give me bonus tokens

**Comment by ThatFruedDued** [comment]
It didn't really do much, it just didn't redirect you when visiting the admin page (`/admin`). However, nothing worked there, it was mainly for niche use cases.
