### ISSUE TITLE
What does the test injectables do diffrent from other

### ISSUE THREAD

**Issue by coolman3289** [ThatFruedDued/blooket-utility-injectables#16]
What does it do?

**Comment by ThatFruedDued** [comment]
Just like the name implies, it was simply an injectable to test the injectable system during development. It stays here for testing purposes.

**Comment by coolman3289** [comment]
What will happen if I use it.

**Comment by ThatFruedDued** [comment]
Nothing bad, just a new pref will show up that doesn't do anything
