### ISSUE TITLE
Gxlizzy hacks in injectables stop working.

### ISSUE THREAD

**Issue by coolman3289** [ThatFruedDued/blooket-utility-injectables#20]
Normal ones work, but in injectable, it does not.

**Comment by ThatFruedDued** [comment]
Issue fixed by fixing the Nginx server. Thanks for reporting!

**Comment by coolman3289** [comment]
@ThatFruedDued

**Comment by ThatFruedDued** [comment]
Works fine for me, please send screenshots

**Comment by coolman3289** [comment]
It simply does nothing (clicking on global hacks)

**Comment by coolman3289** [comment]
Oops, I just did not reload
