### ISSUE TITLE
What happened to glixxy

### ISSUE THREAD

**Issue by ufehurh** [ThatFruedDued/blooket-utility-injectables#25]
i have the hacks. Will they still work.Also why were the removed

**Comment by BlooketHackerx** [comment]
Gliz got a cease and desist order from blooket after hacking their twitter
account, and had to take their hacks down to not be sued by blooket.

**Comment by ufehurh** [comment]
A couple things, why did he hack their twitter account? Also gliz is a hacker? And holy shit that is a little stupid. Last thing how did twitter find out? @BlooketHackerx

**Comment by BlooketHackerx** [comment]
Gliz hacked their account to make some kind of point on how good of a
hacker they are, and, yes. Gliz used to make hacks and update them weekly
so yes he was a "Hacker".
The twitter found out because he tweeted that he hacked into it ON THEIR
TWITTER from what I heard.

**Comment by ufehurh** [comment]
hehe thats funny
