### ISSUE TITLE
problem with dark mode

### ISSUE THREAD

**Issue by timmytheman123** [ThatFruedDued/blooket-utility-injectables#28]
![Screenshot 2022-03-23 3 37 13 PM](https://user-images.githubusercontent.com/91916360/159781902-6d1c56aa-3557-414a-b601-b8a338c68dc4.png)

**Comment by ThatFruedDued** [comment]
Sorry, the dark mode isn't perfect (especially with user-created blooks). Unfortunately, this can't be fixed because I am using an external service to provide dark mode.
