### ISSUE TITLE
Add BlooketUI as an officially supported injectable

### ISSUE THREAD

**Issue by smintf** [ThatFruedDued/blooket-utility-injectables#31]
I have just added support for Blooket-Utility in my Multitool https://github.com/Blooketware/BlooketUI

**Comment by ThatFruedDued** [comment]
Wow, great job! Glad another developer other than me is finally using the Blooket Utility's APIs. I will add this to the `README`.

**Comment by ThatFruedDued** [comment]
You also should update the URL in your `injectable.json` to point to itself (`https://raw.githubusercontent.com/Blooketware/BlooketUI/main/blooket-utility/injectable.json`) so the injectable can automatically update itself.

**Comment by smintf** [comment]
Alright, thanks!
