### ISSUE TITLE
Glixzzy is back.

### ISSUE THREAD

**Issue by hxc4life07** [ThatFruedDued/blooket-utility-injectables#34]
Hi.
I hace notice that glixzzy is back. Maybe you can re-enable the glixzzy injectable. I've noticed this because I've searched him some days ago. He has took his hacks from schoolcheats.net and re-worked them.
Thank you FruedDued for working so hard for your community, github community and blooket community!

**Comment by hxc4life07** [comment]
New glixzzy username: GlixzzyBlooketHacks
Link to his user: [github.com/GlixzzyBlooketHacks/](https://github.com/GlixzzyBlooketHacks/Glixzzy.github.io.)

**Comment by coolman3289** [comment]
That’s not real gxlizzy, they say so themselfs. They are just taking hacks from the school cheats website.

**Comment by hxc4life07** [comment]
Oh, I see.
