### ISSUE TITLE
Glixxzy Scripts Update?

### ISSUE THREAD

**Issue by BlooketHackerx** [ThatFruedDued/blooket-utility-injectables#4]
I see that something was updated, but I am not too smart so if it does work now I can't seem to add it to the booklet utility configurator. I think it has to be a json file right?

**Comment by XJSWAG** [comment]
Ye

**Comment by BlooketHackerx** [comment]
So how do I use the new mod menu you posted because it says invalid injectable

**Comment by ThatFruedDued** [comment]
Check the `README.md` in the main repo for a tutorial on how to add injectables to the new utility

**Comment by ThatFruedDued** [comment]
Updated! Please reopen if you have any issues.
